### PR TITLE
Added density in Performance Constraints

### PR DESCRIPTION
**Pull request by Tanmay24Mukh**
# Pull Request Checklist
 * Merge in the latest Develop branch changes to your branch
 * Remove .pyc files from your repository:
   * Linux/Mac
     * find . -name *.pyc -delete
   * Windows
     * del /S *.pyc
 * Run automatic regression and makes sure everything is passing
 * Did you make a new regression test that covers your new code?
 * Did you update your docstrings?
 * Did you update your headers to include your name and date?
 * Do a final compare with the Develop branch to be sure what you're changing

### CODE REVIEW

**Comment by michK** [comment]
Hey Tanmay,

Note under the 'Files changed' tab that there are 7 changed files, where a few of them are files that I think were committed by accident that don't really have any changes. Just check next time when you make a commit that you only commit the changes that you actually want to make.

I'll check if there's a way to accept individual files only in a PR.

**Comment by Tanmay24Mukh** [comment]
Hey Michael,

I apologise. I didn't do a git status before I committed the changes. I
just realized. I'll be careful the next time.

Regards,
Tanmay

**Comment by michK** [comment]
No problem at all, I just wanted to point it out. Git was very confusing to me in the beginning and I did these types of things all the time (-:

**Comment by michK** [comment]
Closing PR, making changes manually.

**Pull request closed without merging**
